### ISSUE TITLE
Does not support uMurmur

### ISSUE THREAD

**Issue by NickHu** [perrym5/mumble-ruby#43]
Doesn't support umurmur, perhaps its protocol is slightly different so a header for some messages cannot be discerned causing a crash.
```
/home/nick/.rvm/gems/ruby-2.2.0/gems/mumble-ruby-1.1.2/lib/mumble-ruby/connection.rb:29:in `read_message': undefined method `unpack' for nil:NilClass (NoMethodError)
        from /home/nick/.rvm/gems/ruby-2.2.0/gems/mumble-ruby-1.1.2/lib/mumble-ruby/client.rb:121:in `read'
        from /home/nick/.rvm/gems/ruby-2.2.0/gems/mumble-ruby-1.1.2/lib/mumble-ruby/thread_tools.rb:8:in `block (2 levels) in spawn_thread'
        from /home/nick/.rvm/gems/ruby-2.2.0/gems/mumble-ruby-1.1.2/lib/mumble-ruby/thread_tools.rb:8:in `loop'
        from /home/nick/.rvm/gems/ruby-2.2.0/gems/mumble-ruby-1.1.2/lib/mumble-ruby/thread_tools.rb:8:in `block in spawn_thread'

**Comment by dafoxia** [comment]
umurmur uses celt only. This mumble-ruby has no celt compatibility yet.
You can try my fork until my pull request has been processed.
Keep in mind it is only well tested using celt-ruby and opus-ruby I also forked.

**Comment by NickHu** [comment]
I tried your fork and it still suffers the same issue, it seems to be that the output from @conn.read_message in client.rb (line 132) is nil sometimes which causes the whole thing to die.
If you just make it skip nil instead of trying to process it, the connection times out.

**Comment by christerjohansson** [comment]
I have this issue too (I think), how do I skip the nil-part?
My server is,
Linux mumbler 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux

**Comment by schasse** [comment]
same issue here
